name: bipixapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.1
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^5.0.11
  postgres: ^2.6.1
  bcrypt: ^1.1.3
  flutter_animate: ^4.1.1+1
  page_transition: ^2.0.9
  image_picker: ^0.8.7+5
  validatorless: ^1.2.3
  crypto: ^3.0.3
  google_nav_bar: ^5.0.6
  rxdart: ^0.27.7
  rflutter_alert: ^2.0.6
  get_it: ^7.6.0
  cloud_firestore: ^4.8.0
  google_mobile_ads: ^3.0.0
  firebase_core: ^2.13.1
  flutter_zoom_videosdk: 
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.6
  dart_jsonwebtoken: ^2.4.2
  shared_value: ^3.0.0
  events_emitter: ^0.5.2
  permission_handler: ^10.2.0
  google_fonts: ^4.0.3
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.3


flutter_icons:
  image_path: "assets/app_icon/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#0472E8"
  adaptive_icon_foreground: "assets/app_icon/icon_android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/tic_tac_toe/
    - assets/images/games_logos/
    - assets/images/checkers/
    - assets/images/payment/
    - assets/images/social_media_icons/
    - assets/app_icon/
    
    

   

